_id: 8549c990-7631-11e7-afac-b124940f35fd
metadata:
  author: Daniel Wheeler
  email: daniel.wheeler2@gmail.com
  simulation_name: test_sim
  summary: My test sim
  timestamp: '30 July, 2017'
  implementation:
    repo:
      url: 'https://github.com/wd15/mks-tutorial'
      version: aaaaaaaaaa
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '1'
    cores: '1'
    nodes: '1'
  software:
    name: custom
    version: '1'
    repo:
      url: 'https://github.com/wd15/mks-tutorial'
      version: aaaaaaaaa
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1a_wrksttn.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - wall_time: '1'
        sim_time: '1'
  - name: memory_usage
    values:
      - unit: KB
        value: '1e7'
date: 1501534072
