_id: e5ae83b0-75fb-11e7-afac-b124940f35fd
metadata:
  author: Daniel Wheeler
  email: daniel.wheeler2@gmail.com
  simulation_name: test_sim
  summary: testing the form and that it still works
  timestamp: '1 July, 2017'
  implementation:
    repo:
      url: 'https://github.com/wd15/mks-tutorial'
      version: 0f1b6648978f6
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '2.5'
    cores: '1'
    nodes: '1'
  software:
    name: custom
    version: ''
    repo:
      url: 'https://github.com/wd15/mks-tutorial'
      version: 0f1b6648978f6
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/dschwen/75c5f5f47519119fdb6e934056f6fd56/raw/d865f3213e4a695dc031c37e71b280248c4a0eb5/problem_1b_out.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - time: '1.0'
        sim_time: '1.0'
  - name: memory_usage
    values: '1000000'
date: 1501511041
