---
_id: 1abf01c0-76f5-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6a
  version: '0'
data:
- format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/0e6057ada4de47098d5d39a27d8866ab/raw/fc51bc61c389df0b21341781e5f60bd098e09aa5/energy_6a_dx10.csv
- name: run_time
  values:
  - sim_time: '1000'
    wall_time: '32640'
- name: memory_usage
  values:
  - unit: KB
    value: '2500'
date: 1501618075
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: '3.50'
    cores: '12'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: threaded
  implementation:
    container_url: ''
    name: mmsp
    repo:
      url: https://github.com/tkphd/CHiMaD-Hackathon/tree/master/Workshop5/electrochem
      version: f35b6a0
  simulation_name: mmsp_6a_wrksttn
  summary: MMSP 12-core workstation, red-black Gauss-Seidel solver, dx=1.0, dt=0.05,
    CFL=240
  timestamp: 28 July, 2017
