_id: 93113e00-0c5e-11e8-b653-4f1ed6519c85
benchmark:
  id: 4a
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '1500'
    wall_time: '266576'
- name: memory_usage
  values:
  - unit: KB
    value: '2000000'
- description: All data
  format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: all_data
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_free_energy
    type: formula
  type: line
  url: https://raw.githubusercontent.com/wd15/sfepy-bm4/5284b38ceb6f1bcadac90f546c651c06f8ce7261/time.csv
- description: Contour data
  format:
    parse:
      x: number
      y: number
    type: csv
  name: contour
  type: line
  url: https://raw.githubusercontent.com/wd15/sfepy-bm4/5284b38ceb6f1bcadac90f546c651c06f8ce7261/contour.csv
date: 1518046097
layout: post
message: ' '
metadata:
  author:
    email: daniel.wheeler2@gmail.com
    first: Daniel
    github_id: wd15
    last: Wheeler
  hardware:
    acc_architecture: none
    clock_rate: '3.2'
    cores: '1'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: sfepy
    repo:
      url: https://github.com/wd15/sfepy-bm4/
      version: 5284b38ceb6f1bcadac90f546c651c06f8ce7261
  summary: >-
    Sfepy and FiPy implementation of benchmark 4a on a 400x400 grid.
    The results seem very different from the paper.
  timestamp: 2 February, 2018
