// Generated by CoffeeScript 1.4.0
(function() {
  var add_description, add_header, add_icon, add_icons, add_logo, add_stats, build_function, data_file, icons;

  data_file = "data/codes.json";

  add_logo = function(selection) {
    var subselection;
    subselection = selection.filter(function(d) {
      return "logo" in d;
    });
    subselection = subselection.append("div").attr("class", "logo");
    return subselection.append("img").attr("src", function(d) {
      return d.logo;
    });
  };

  add_header = function(selection) {
    var subselection;
    subselection = selection.filter(function(d) {
      return "name" in d;
    });
    return subselection.append("h4").attr("class", "codeheader").text(function(d) {
      return d.name;
    });
  };

  add_description = function(selection) {
    var subselection;
    subselection = selection.filter(function(d) {
      return "description" in d;
    });
    return subselection.append("p").text(function(d) {
      return d.description;
    });
  };

  add_stats = function(selection) {
    var subselection, table, tr;
    subselection = selection.filter(function(d) {
      return "stats" in d;
    });
    subselection.append("h5").text("Stats");
    table = subselection.append("table").attr("class", "indent");
    tr = table.selectAll().data(function(d) {
      return d.stats;
    }).enter().append("tr");
    tr.append("td").html(function(d) {
      return d.name + ":&nbsp;";
    });
    return tr.append("td").text(function(d) {
      return d.value;
    });
  };

  icons = {
    GitHub: {
      html: '<i class="fa fa-github fa-2x"></i>'
    },
    Home: {
      html: '<i class="fa fa-home fa-2x"></i>'
    },
    OpenHub: {
      html: '<img src="images/OH_logo-24x24.png" class="icon">'
    }
  };

  add_icon = function(selection) {
    var subselection;
    subselection = selection.filter(function(d) {
      return d.name in icons;
    });
    subselection.attr("href", function(d) {
      return d.url;
    });
    subselection.attr("title", function(d) {
      return d.name;
    });
    return subselection.html(function(d) {
      return icons[d.name].html;
    });
  };

  add_icons = function(selection) {
    var a, div, subselection;
    subselection = selection.filter(function(d) {
      return "links" in d;
    });
    div = subselection.append("div").attr("class", "icons");
    a = div.selectAll().data(function(d) {
      return d.links;
    }).enter().append("a");
    return add_icon(a);
  };

  build_function = function(data) {
    var selection;
    console.log(data);
    selection = d3.select("#codes").selectAll().data(data).enter().append("div").attr("class", "col-md-4").append("div").attr("class", "card");
    add_logo(selection);
    add_header(selection);
    add_description(selection);
    add_stats(selection);
    return add_icons(selection);
  };

  d3.json(data_file, build_function);

}).call(this);
