// Generated by CoffeeScript 1.4.0
(function() {
  var build_function, data_file, template;

  data_file = "data/codes.json";

  template = Handlebars.templates.codes;

  build_function = function(data) {
    var selection;
    selection = d3.select("#codes").selectAll().data(data).enter().append("div").attr("class", "col-md-4").append("div").attr("class", "card");
    selection.append("div").attr("class", "test");
    return selection.append("div").attr("class", "test1").html(function(d) {
      return template(d);
    });
  };

  d3.json(data_file, build_function);

}).call(this);
