# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
{ pkgs, pypkgs }:
rec {
  requests_mock = pypkgs.buildPythonPackage rec {
    version = "1.10.0";
    pname = "requests-mock";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-WcnDJBmp+xroPsJC2Y6InEW9fXpl1IN1zCQ+wIRBZYs=";
    };
    doCheck = false;
    buildInputs = with pypkgs; [ pbr requests six ];
    propagatedBuildInputs = buildInputs;
  };

  itables = pypkgs.buildPythonPackage rec {
    pname = "itables";
    version = "0.4.6";

    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-XiLxeYHR8a3QqiyA+azC5O157XuRGvgb+exU1h7aAck=";
    };

    doCheck = false;

    propagatedBuildInputs = [ pypkgs.ipykernel pypkgs.pandas pypkgs.requests ];
  };

  more_click = pypkgs.buildPythonPackage rec {
    pname = "more_click";
    version = "0.1.2";
    format = "pyproject";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-CF2mbVqbgjxdkSqIjcofoMizoU7Rsh6pyKG4FIV6OYE=";
    };
    doCheck = true;

    propagatedBuildInputs = with pypkgs; [
      setuptools
      click
    ];
  };

  pystow = pypkgs.buildPythonPackage rec {
    pname = "pystow";
    version = "0.5.0";
    format = "pyproject";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-SQ6ey+T5R8cvYyl/Q/ZYQyPJyi8tSNR/KiKoFdxVK7Q=";
    };
    doCheck = true;

    propagatedBuildInputs = with pypkgs; [
      setuptools
      requests
      tqdm
      click
    ];
  };

  zenodo_client = pypkgs.buildPythonPackage rec {
    pname = "zenodo_client";
    version = "0.3.2";
    format = "pyproject";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-prA43n0WgDbTIo8hjhq245OgrJ2vwtk8x9Vwsrz83hU=";
    };

    doCheck = true;

    propagatedBuildInputs = with pypkgs; [
      setuptools
      typing-extensions
      click
      more_click
      pystow
      pydantic
    ];
  };

  dotwiz = pypkgs.buildPythonPackage rec {
    pname = "dotwiz";
    version = "0.2.0";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-fkCqvaaxUElNBYk9HKCOqQRlOFWJRh3VvG2//1IIizs=";
    };

    doCheck = false;

    propagatedBuildInputs = with pypkgs; [
    ];
  };

  click_params = pypkgs.buildPythonPackage rec {
    pname = "click_params";
    version = "0.4.1";
    src = pypkgs.fetchPypi {
      inherit pname version;
      sha256 = "sha256-PI1ktLzqeDOFtCkk+f8pMtYZuNpLyUawNn1Ylvcvuhg=";
    };

    doCheck = false;

    propagatedBuildInputs = with pypkgs; [
      validators
      click
    ];
  };

}
