benchmark:
  id: 1b
  version: 1
data:
- name: run_time
  transform:
  - expr: datum.value_m * 1024.0
    field: value
    type: formula
  values:
  - sim_time: 2924
    wall_time: 2471
- name: memory_usage
  values:
  - unit: GB
    value: 100
- format:
    parse:
      f_density: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.f_density
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/simopier/739e1e4cb6e3682badee62dbb242fd98/raw/ec506181dfd410da88ca3760fd800fe930e48338/moose_psu_1b_STA.csv
metadata:
  author:
    first: PC.
    last: Simon
  email: pjs5523@psu.edu
  github_id: simopier
  hardware:
    architecture: x86_64
    cores: 80
    details:
    - name: clock rate
      values:
        rate: null
        unit: GHz
    - name: processor
      values: ''
  implementation:
    details:
    - name: time_stepper
      values: STA
    end_condition: Time limit
    repo:
      url: https://github.com/simopier/CHiMaD/blob/master/H4.i
      version: '724999206'
  software:
    name: moose
    version: git commit 2593a61 on 2017-01-18
  summary: Metadata for the Benchmark1 problems
  timestamp: Wed Feb  8 14:38:00 EST 2017
