_id: c11b2720-76e5-11e7-a3e9-cb63094aa20f
metadata:
  author: Daniel Wheeler
  email: daniel.wheeler2@gmail.com
  simulation_name: demo_sim_1a_a
  summary: A demo simulation for phase field workshop using fmks code
  timestamp: '1 August, 2017'
  implementation:
    repo:
      url: 'https://gist.github.com/wd15/ce3c8620fd19ba58f80e4f35da562dda'
      version: 35503a64b632
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '2.5'
    cores: '1'
    nodes: '1'
  software:
    name: custom
    version: ''
    repo:
      url: 'https://github.com/wd15/fmks'
      version: 703185ee0e487e
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/wd15/ce3c8620fd19ba58f80e4f35da562dda/raw/d2e5e281695dc031f4f888fb1edae326b447ad34/free_energy_demo_1.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - wall_time: '8.35'
        sim_time: '199.8'
  - name: memory_usage
    values:
      - unit: KB
        value: '123289'
date: 1501611482
