---
benchmark:
  id: 1a
  version: 1
data:
- name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - free_energy: 319.09096487896744
    time: 0.0
  - free_energy: 318.83057833279986
    time: 0.9834705943388384
  - free_energy: 283.6148043822506
    time: 10.432280700761654
  - free_energy: 207.903541306264
    time: 20.81378117476748
  - free_energy: 197.39411290020013
    time: 27.567792571902892
  - free_energy: 188.64120084392533
    time: 33.79300496867283
  - free_energy: 178.87382145157355
    time: 40.24119682471971
  - free_energy: 169.26132300018622
    time: 46.746063504583994
  - free_energy: 162.25546973386005
    time: 52.746625481564735
- name: run_time
  values:
  - sim_time: 52.746625481564735
    wall_time: 1495.47
- name: memory_usage
  values:
  - unit: KB
    value: 470976
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 1
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: fipy
    repo:
      url: https://github.com/usnistgov/FiPy-spinodal-decomposition-benchmark/tree/master/periodic/
      version: 944284638f00c3a411a71981d27becf97a2eb0e4
  summary: Serial Travis CI benchmark with FiPy, periodic domain
  timestamp: Tue, 10 Jan 2017 00:46:24 +0000
