_id: db3a3fe0-f586-11e7-b7eb-1faff7702040
metadata:
  author:
    first: Trevor
    last: Keller
    email: trevor.keller@nist.gov
    github_id: tkphd
  simulation_name: fipy_1a_travis
  timestamp: 'Tue, 10 Jan 2017 00:46:24 +0000'
  summary: 'Serial Travis CI benchmark with FiPy, periodic domain'
  implementation:
    name: fipy
    repo:
      url: >-
        https://github.com/usnistgov/FiPy-spinodal-decomposition-benchmark/tree/master/periodic/
      version: 944284638f00c3a411a71981d27becf97a2eb0e4
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: gpu
    parallel_model: threaded
    clock_rate: '2.3'
    cores: '2'
    nodes: '3'
benchmark:
  id: 1a
data:
  - name: run_time
    values:
      - wall_time: '1495.47'
        sim_time: '52.746625481564735'
  - name: memory_usage
    values:
      - unit: KB
        value: '470976'
  - name: wow
    url: >-
      https://gist.githubusercontent.com/simopier/739e1e4cb6e3682badee62dbb242fd98/raw/ec506181dfd410da88ca3760fd800fe930e48338/moose_psu_1d_IA.json
    format:
      type: json
      parse:
        time: number
        free_energy: number
    description: blah
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.free_energy
        as: 'y'
  - name: contour_from_file
    url: >-
      https://gist.githubusercontent.com/wd15/daa604e1846433c0723129504c8b7c09/raw/c01c102f9823fba27888b503b8b0bb2aa42ac74d/contour.csv
    format:
      type: csv
      parse:
        x: number
        'y': number
        z: number
    description: test csv data
    type: contour
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
      - type: formula
        expr: datum.z
        as: z
  - name: image0
    url: >-
      http://www.cradlekennels.co.za/jack-russells/_images/puppies/jack_russell_puppy_12.jpg
    type: image
    description: A puppy picture
  - name: youtube
    url: 'https://www.youtube.com/embed/Q8TXgCzxEnw?rel=0'
    type: youtube
    description: My youtube video
date: 1515534521
