_id: ea08b140-a2fb-11e9-bb98-afd93fcf5e8e
metadata:
  author:
    first: Shubhajit
    last: Mondal
    email: sm44@iitbbs.ac.in
    github_id: smondal44
  timestamp: '29 June, 2019'
  summary: >-
    In this problem, we solve the linear elasticity problem for circular
    heterogeneous precipitate in effectively infinite domain.
  implementation:
    name: Fenics
    repo:
      url: >-
        https://github.com/smondal44/Linear-Elasticity/blob/master/r_Cir_htr_s.py
      version: 930c244c0019aed533f30cdd7105bac8a179d41e
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: '2.4'
    cores: '1'
    nodes: '1'
benchmark:
  id: 4c
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '36000'
        sim_time: '36000'
  - name: memory_usage
    values:
      - unit: KB
        value: '8388608'
  - name: contour
    url: 'https://drive.google.com/open?id=1mEbio1E7t7-wqRFSlI8f4gbzgY4JXyxR'
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: >-
      The data file contains the coordinate of the contour plot at equilibrium
      considering the the order parameter value=0.5
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
  - name: all_data
    url: 'https://drive.google.com/open?id=1wypfG6lOSeLHiAJzIggPpwqWa5rVAsV8'
    format:
      type: csv
      parse:
        Time: number
        "Total Energy": number
    description: >-
      Here, the time, elastic, bulk, gradient, total free energy of the system
      are included in the data file in csv format.
    type: line
    transform:
      - type: formula
        expr: datum.Time
        as: x
      - type: formula
        expr: "datum['Total Energy']"
        as: 'y'
  - name: Energy_plot1
    url: 'https://drive.google.com/open?id=1xkeSuwNOdC_W8KC1XMkpsoKLtBUx-49S'
    type: image
    description: Evolution of the elastic energy has been plotted as function of log(time)
  - name: Energy_plot2
    url: 'https://drive.google.com/open?id=1UYKdkTsPmZAvy1jwk_50-PEXpQcByBss'
    type: image
    description: >-
      Evolution of the total free energy has been plotted as function of
      log(time)
date: 1562753846
