---
_id: c67a5650-76f9-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6a
  version: '0'
data:
- description: Free Energy Plot
  format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/laagesen/d8ed181db58d77625336461c21f989b3/raw/9e5679ea74730616d7ee39fb7900a00e1bcc02a6/problem2a_out_160_dtIA8_upload.csv
- name: run_time
  values:
  - sim_time: '400'
    wall_time: '495'
- name: memory_usage
  values:
  - unit: B
    value: '800000000'
date: 1501620081
metadata:
  author:
    email: Larry.Aagesen@inl.gov
    first: Larry
    github_id: laagesen
    last: Aagesen
  hardware:
    acc_architecture: none
    clock_rate: '2.7'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/dschwen/CHiMaD_Hackathon
      version: 4b543d98c423fa719d360c16edf70960477c09d7
  simulation_name: inl_moose_6a
  summary: Benchmark problem 6a, energy vs time. 160 x 160 uniform mesh, iteration
    adaptive time stepping, target iterations=8
  timestamp: 26 July, 2017
