---
benchmark:
  id: 1a
  version: 1
data:
- name: timestep
  values: 0.00104167
- format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1a_wrksttn.csv
- name: run_time
  values:
  - sim_time: 53333.3
    wall_time: 157186.74
- name: memory_usage
  values:
  - unit: KB
    value: 28600
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 12
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: mmsp
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/periodic/
      version: 4c3af04ac4e46665eacc599b0d2cc8b4a9963461
  summary: MPI parallel workstation benchmark with MMSP, periodic domain
  timestamp: Fri, 10 Feb 2017 13:34:42 -0500
