_id: 37abb750-5ba6-11e9-9ffc-138c3ba5b300
metadata:
  author:
    first: adsfasdf
    last: kjhkjhkjhk
    email: daniel.wheeler2@gmail.com
    github_id: wd15
  timestamp: '9 April, 2019'
  summary: jhiuyhiuhi
  implementation:
    name: fipy
    repo:
      url: 'https://github.com/usnistgov/pfhub'
      version: 7064afd286bf6cefaf11086b07dbd4f58dfdbca1
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '10'
    cores: '1'
    nodes: '1'
benchmark:
  id: 7a
  version: '0'
data:
  - name: run_time
    values:
      - wall_time: '67'
        sim_time: '76'
  - name: memory_usage
    values:
      - unit: KB
        value: '76'
date: 1554910507
