_id: 3295bc80-7673-11e7-afac-b124940f35fd
metadata:
  author: Daniel Wheeler
  email: daniel.wheeler2@gmail.com
  simulation_name: demo_1a
  summary: Demo simulation with bad data
  timestamp: '1 August, 2017'
  implementation:
    repo:
      url: 'https://gist.github.com/wd15/ce3c8620fd19ba58f80e4f35da562dda'
      version: 26c7468abbda
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '1.6'
    cores: '1'
    nodes: '1'
  software:
    name: custom
    version: ''
    repo:
      url: 'https://github.com/wd15/fmks'
      version: 703185ee0e4
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/wd15/ce3c8620fd19ba58f80e4f35da562dda/raw/26c7468abbdae5a72732c0924a8257bbe40a7962/free_energy.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - wall_time: '7.97'
        sim_time: '1000.0'
  - name: memory_usage
    values:
      - unit: KB
        value: '119388'
date: 1501562280
