---
_id: a76de900-76f6-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6a
  version: '0'
data:
- description: Free Energy Plot
  format:
    parse:
      Energy: number
      Time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.Energy
    type: formula
  - as: x
    expr: datum.Time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/23c6f2d74c4c41d8da883feee30efdee/raw/12633176adddfb4375c780cfa10678d251520d3d/energy_6a.csv
- name: run_time
  values:
  - sim_time: '400'
    wall_time: '507'
- name: memory_usage
  values:
  - unit: KB
    value: '124000'
date: 1501618740
metadata:
  author:
    email: dmontiel@umich.edu
    first: David
    github_id: david-montiel-t
    last: Montiel
  hardware:
    acc_architecture: none
    clock_rate: '2.6'
    cores: '16'
    cpu_architecture: x86_64
    nodes: '2'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: prisms
    repo:
      url: https://github.com/prisms-center/phaseField/tree/v2.0pre/applications/cahnHilliard_electrostatics
      version: 8a75a0f27bc157430f7fbe623265c120724d9ce5
  simulation_name: prismspf_6a_flux_med
  summary: Solution to the 6a benchmark problem with an intermediate level of refinement.  Run
    on PRISMS dedicated hardware at the University of Michigan's Flux supercomputing
    cluster.
  timestamp: 28 July, 2017
