_id: 79de10c0-000e-11ea-a6eb-a5e3c4b29a60
metadata:
  author:
    first: Jean-Luc
    last: Fattebert
    email: fattebertj@ornl.gov
    github_id: jeanlucf22
  timestamp: '5 November, 2019'
  summary: "Finite volume discretization. Time integration: Backward Euler, Jacobian-Free Newton Krylov solver,  with multigrid preconditioning. Adaptive time-stepping (up to dt=3.2).\r\nUniform mesh 1440 x 1440."
  implementation:
    name: AMPE
    repo:
      url: 'https://github.com/LLNL/AMPE'
      version: 350d0b1ada9b83ce0479d41056e8ea5f29109b21
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '2.3'
    cores: '64'
    nodes: '2'
benchmark:
  id: 3a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1033'
        sim_time: '1500'
  - name: memory_usage
    values:
      - unit: KB
        value: '2980000'
  - name: Free_Energy
    url: >-
      https://github.com/LLNL/AMPE/tree/release/benchmarks/PFHub3/free_energy.csv
    format:
      type: csv
      parse:
        Time: number
        Free energy: number
    description: Free energy vs. time
    type: line
    transform:
      - type: formula
        expr: datum.Time
        as: x
      - type: formula
        expr: datum.Free energy
        as: 'y'
  - name: phase_field_1500
    url: >-
      https://github.com/LLNL/AMPE/tree/release/benchmarks/PFHub3/phase_field_1500.csv
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: Contour at t=1500
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
  - name: Solid_fraction
    url: >-
      https://github.com/LLNL/AMPE/tree/release/benchmarks/PFHub3/solid_fraction.csv
    format:
      type: csv
      parse:
        time: number
        solid fraction: number
    description: Solid fraction vs. time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.solid fraction
        as: 'y'
  - name: Tip_position
    url: >-
      https://github.com/LLNL/AMPE/tree/release/benchmarks/PFHub3/tip_position.csv
    format:
      type: csv
      parse:
        time: number
        tip position: number
    description: Tip position vs. time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.tip position
        as: 'y'
date: 1572987276
