_id: 72aa5190-76f1-11e7-a3e9-cb63094aa20f
metadata:
  author: kjlkjlkj
  email: a@b
  simulation_name: afafasdas
  summary: aaaaaaaaaaaaaa
  timestamp: '1 August, 2017'
  implementation:
    repo:
      url: 'https://github.com/wd15/mks-tutorial'
      version: aaaaaaaaaa
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '1'
    cores: '1'
    nodes: '1'
  software:
    name: custom
    version: '1'
    repo:
      url: 'https://github.com/wd15/mks-tutorial'
      version: aaaaaaaaa
benchmark:
  id: 6a
  version: '0'
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/dschwen/75c5f5f47519119fdb6e934056f6fd56/raw/d865f3213e4a695dc031c37e71b280248c4a0eb5/problem_1b_out.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - wall_time: '1'
        sim_time: '1'
  - name: memory_usage
    values:
      - unit: KB
        value: '1'
date: 1501616504
