_id: 758384d0-1eff-11ec-a167-1d8e62164deb
metadata:
  author:
    first: Blondell Newcombe
    last: Audry Kent
    email: florentinawooldridge@yahoo.com
    github_id: Monika Brumby
  timestamp: '15'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Florentina
    repo:
      url: 'https://irmusic4.ir/id/1358/'
      version: TK
    container_url: 'https://irmusic4.ir/id/1358/'
  hardware:
    cpu_architecture: mipsel
    acc_architecture: gpu
    parallel_model: serial
    clock_rate: YC
    cores: '1'
    nodes: PR
benchmark:
  id: 8c
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: LF
        sim_time: UT
  - name: memory_usage
    values:
      - unit: KB
        value: XM
date: 1632684308
