---
benchmark:
  id: 1a
  version: 1
data:
- name: free_energy
  url: https://github.com/mfrichtl/PFHub_benchmarks/blob/main/problems/pfhub_benchmark_1.a1_csv.csv
  format:
    type: csv
    parse:
      total_energy: number
      time: number
  transform:
    - type: formula
      field: free_energy
      expr: datum.total_energy
    - type: filter
      test: "datum.time < 1e6"
- name: run_time
  values:
  - sim_time: 225023
    wall_time: 6308.207
- name: memory_usage
  values:
  - unit: KB
    value: 124000
metadata:
  author:
    email: mfrichtl@visionpointsystems.com
    first: Matthew
    github_id: mfrichtl
    last: Frichtl
  hardware:
    acc_architecture: none
    clock_rate: 3.6
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: distributed
  implementation:
    name: moose
    repo:
      url: https://github.com/mfrichtl/PFHub_benchmarks
      version: 4dd0a8508d174c416ecd3105805f94852e1af0f9
  summary: MPI parallel workstation benchmark with MOOSE
  timestamp: Sat, 21 Jan 2023 14:30:00 -0500
