---
benchmark:
  id: 1a
  version: 1
data:
- name: free_energy
  url: https://raw.githubusercontent.com/mfrichtl/PFHub_benchmarks/main/problems/pfhub_benchmark_1.a1_csv.csv
  format:
    type: csv
    parse:
      total_energy: number
      time: number
  transform:
    - as: y
      type: formula
      expr: datum.total_energy
    - as: x
      type: formula
      expr: datum.time
- name: run_time
  values:
  - sim_time: 1000000
    wall_time: 1774.630
- name: memory_usage
  values:
  - unit: KB
    value: 1671430
metadata:
  author:
    email: mfrichtl@visionpointsystems.com
    first: Matthew
    github_id: mfrichtl
    last: Frichtl
  hardware:
    acc_architecture: none
    clock_rate: 3.6
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: distributed
  implementation:
    name: moose
    repo:
      url: https://github.com/mfrichtl/PFHub_benchmarks
      version: e8e96c25e69256ae0b9c7fe9f5fdfd6eb5ab70fc
  summary: MPI parallel workstation benchmark with MOOSE
  timestamp: Sat, 4 Feb 2023 15:40:00 -0500
