benchmark:
  id: 1a
  version: 1
data:
- name: memory_usage
  values:
    unit: GB
    value: 100
- name: run_time
  transform:
  - expr: datum.value_m * 1024.0
    field: value
    type: formula
  values:
  - sim_time: 526338
    wall_time: 3964
- format:
    parse:
      f_density: number
      time: number
    type: csv
  name: free_energy
  transform:
  - expr: datum.f_density
    field: free_energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/simopier/739e1e4cb6e3682badee62dbb242fd98/raw/ec506181dfd410da88ca3760fd800fe930e48338/moose_psu_1a_IA.csv
metadata:
  author: PC. Simon
  email: pjs5523@psu.edu
  github_id: ''
  hardware:
    architecture: x86_64
    cores: 40
    details:
    - name: clock rate
      values:
        rate: null
        unit: GHz
    - name: processor
      values: ''
  implementation:
    details:
    - name: time_stepper
      values: IA
    end_condition: Equilibrium, total energy fluctuated due to numerical noise
    repo:
      url: https://github.com/simopier/CHiMaD/blob/master/H1.i
      version: '724999206'
  software:
    name: moose
    version: git commit 2593a61 on 2017-01-18
  summary: Metadata for the Benchmark1 problems
  timestamp: Thu Jan 19 15:21:30 EST 2017
