_id: cd4510a0-26be-11ec-83ae-a7d1de7d239e
metadata:
  author:
    first: Denise Bertles
    last: Frederick Gouin
    email: simonebreton@yahoo.de
    github_id: Cooper Ligertwood
  timestamp: '27'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Simone
    repo:
      url: >-
        https://funkhabari.ir/2021/08/03/%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d9%85%d8%a7%d9%86%db%8c%d8%aa%d9%88%d8%b1-%d8%a7%db%8c%d8%b3%d9%88%d8%b3-va24ehe%d8%9b-%d8%ae%d9%88%d8%b4-%d9%82%db%8c%d9%85%d8%aa%db%8c-%d8%ac%d8%af%db%8c%d8%af-%d8%af/
      version: ML
    container_url: >-
      https://funkhabari.ir/2021/08/03/%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d9%85%d8%a7%d9%86%db%8c%d8%aa%d9%88%d8%b1-%d8%a7%db%8c%d8%b3%d9%88%d8%b3-va24ehe%d8%9b-%d8%ae%d9%88%d8%b4-%d9%82%db%8c%d9%85%d8%aa%db%8c-%d8%ac%d8%af%db%8c%d8%af-%d8%af/
  hardware:
    cpu_architecture: sh4eb
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: UV
    cores: '1'
    nodes: BP
benchmark:
  id: 4c
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: PC
        sim_time: PG
  - name: memory_usage
    values:
      - unit: KB
        value: RO
date: 1633536147
