---
benchmark:
  id: fake
  version: 1
data:
- name: timestep
  values: 0.00195312
- format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1a_wrksttn.csv
  boxuid: "00000000-0000-4000-a000-000000000000"
- name: run_time
  values:
  - sim_time: 53333.3
    wall_time: 170618.87
- name: memory_usage
  values:
  - unit: KB
    value: 27232
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 3.5
    cores: 6
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: distributed
  implementation:
    container_url: http://docker.com/my_container
    name: mmsp
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/periodic
      version: b949fbc4116f020db619fe1ccacbf8b13dfd5e32
  summary: MPI parallel workstation benchmark with MMSP
  timestamp: Thu, 22 Dec 2016 15:20:53 -0500
