_id: a5daf110-0b93-11ec-806c-6708a4dea875
metadata:
  author:
    first: Miguel Abrams
    last: John Summerfield
    email: busterhoule@moose-mail.com
    github_id: Christiane Benjafield
  timestamp: '25'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Buster
    repo:
      url: >-
        https://Varzeshikhabari.ir/2021/07/22/%d8%af%d8%b3%d8%aa-%d9%81%d9%88%d9%84%d8%a7%d8%af-%d9%88-%d8%aa%db%8c%d9%85-%d9%87%d8%a7%db%8c-%d9%86%d9%81%d8%aa%db%8c-%d8%ae%d9%88%d8%b2%d8%b3%d8%aa%d8%a7%d9%86-%d8%a7%d8%b2-%d9%86%d8%b8%d8%b1/
      version: OL
    container_url: >-
      https://Varzeshikhabari.ir/2021/07/22/%d8%af%d8%b3%d8%aa-%d9%81%d9%88%d9%84%d8%a7%d8%af-%d9%88-%d8%aa%db%8c%d9%85-%d9%87%d8%a7%db%8c-%d9%86%d9%81%d8%aa%db%8c-%d8%ae%d9%88%d8%b2%d8%b3%d8%aa%d8%a7%d9%86-%d8%a7%d8%b2-%d9%86%d8%b8%d8%b1/
  hardware:
    cpu_architecture: mipsel
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: VV
    cores: '1'
    nodes: 'NO'
benchmark:
  id: 3a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: YJ
        sim_time: ER
  - name: memory_usage
    values:
      - unit: KB
        value: FO
date: 1630548931
