---
benchmark:
  id: fake
  version: 1
data:
- description: my free energy plot
  format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1a_wrksttn.csv
- name: run_time
  values:
  - sim_time: 53333.3
    wall_time: 170618.87
- name: memory_usage
  values:
  - unit: KB
    value: 27232
metadata:
  author:
    email: alias@organization.com
    first: Given name
    github_id: Users Github ID
    last: Surname
  hardware:
    acc_architecture: none
    clock_rate: 2.7
    cores: 6
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: serial
  implementation:
    container_url: ''
    name: fipy
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/periodic
      version: b949fbc4116f020db619fe1ccacbf8b13dfd5e32
  summary: concise description of this contribution
  timestamp: Mon, 10 Mar 1982 15:03:32 -0500
