_id: 1877d0c0-6013-11e7-99f0-07446257ec6f
metadata:
  author: ''
  email: ''
  name: ''
  summary: ''
  timestamp: ''
  implementation:
    repo:
      url: ''
      version: ''
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: ''
    cores: '1'
    nodes: '1'
  software:
    version: ''
    repo:
      url: ''
      version: ''
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1a_wrksttn.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - time: '76876'
        sim_time: '876876'
  - name: youtube
    url: 'https://www.youtube.com/watch?v=RGqvWEoaZ6c'
  - name: memory_usage
    values: '876876876'
date: 1499102079
test_field: hi1!
another_field:
  - sub_field: 3
another_field1: stuff
