_id: 2fe75e40-153a-11ea-b835-9d4c1360ea39
metadata:
  author:
    first: Daniel
    last: Wheeler
    email: daniel.wheeler2@gmail.com
    github_id: wd15
  timestamp: '2 February, 2018'
  summary: >-
    Sfepy and FiPy implementation of benchmark 4a on a 400x400 grid. The results
    seem very different from the paper.
  implementation:
    name: sfepy
    repo:
      url: 'https://github.com/wd15/sfepy-bm4/'
      version: 5284b38ceb6f1bcadac90f546c651c06f8ce7261
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '3.2'
    cores: '1'
    nodes: '1'
benchmark:
  id: 4a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '266576'
        sim_time: '1500'
  - name: memory_usage
    values:
      - unit: KB
        value: '2000000'
  - name: all_data
    url: >-
      https://raw.githubusercontent.com/wd15/sfepy-bm4/5284b38ceb6f1bcadac90f546c651c06f8ce7261/time.csv
    format:
      type: csv
      parse:
        time: number
        total_free_energy: number
    description: All data
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_free_energy
        as: 'y'
  - name: contour
    url: >-
      https://raw.githubusercontent.com/wd15/sfepy-bm4/5284b38ceb6f1bcadac90f546c651c06f8ce7261/contour.csv
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: Contour data
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
date: 1575315024
