_id: 070dfdb0-aada-11e8-b71a-21cf527883e3
metadata:
  author:
    first: Trevor
    last: Keller
    email: trevor.keller@nist.gov
    github_id: tkphd
  timestamp: 'Tue, 10 Jan 2017 01:27:20 +0000'
  summary: 'Serial Travis CI benchmark with FiPy, T-shape domain'
  implementation:
    name: fipy
    repo:
      url: >-
        https://github.com/usnistgov/FiPy-spinodal-decomposition-benchmark/tree/master/T-shape/
      version: 944284638f00c3a411a71981d27becf97a2eb0e4
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '1'
    nodes: '1'
benchmark:
  id: 1c
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '320.29'
        sim_time: '463.10144410049776'
  - name: memory_usage
    values:
      - unit: KB
        value: '306448'
date: 1535471403
