_id: 3856fd10-0c1d-11e8-b653-4f1ed6519c85
metadata:
  author:
    first: Stephen
    last: DeWitt
    email: stvdwtt@umich.edu
    github_id: stvdwtt
  timestamp: ''
  summary: >-
    Initial run of Benchmark 7 using PRISMS-PF. This simulation uses quadratic
    elements (3rd order accurate in space) and forward Euler time stepping (1st
    order in time).
  implementation:
    name: PRISMS-PF
    repo:
      url: >-
        https://github.com/prisms-center/phaseField/tree/master/applications/CHiMaD_benchmark7
      version: 7cdde5a5c48ef64b6a9d2454836ce3c784f222a5
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '3.5'
    cores: '6'
    nodes: '1'
benchmark:
  id: 7a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '0'
        sim_time: '0'
  - name: memory_usage
    values:
      - unit: KB
        value: '0'
  - name: spatial_quad
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm7a_spatial_quad.csv'
    format:
      type: csv
      parse:
        mesh_size: number
        L2_error: number
    description: >-
      Data for spatial convergence test using quadratic elements. The time step
      is constant at 2e-4 for all tests.
    type: line
    transform:
      - type: formula
        expr: datum.mesh_size
        as: x
      - type: formula
        expr: datum.L2_error
        as: 'y'
  - name: temporal_quad
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm7a_temporal_quad.csv'
    format:
      type: csv
      parse:
        time_step: number
        L2_error: number
    description: >-
      Data for temporal convergence test using quadratic elements. The time step
      is constant at 2.6e-3 for all tests.
    type: line
    transform:
      - type: formula
        expr: datum.time_step
        as: x
      - type: formula
        expr: datum.L2_error
        as: 'y'
date: 1518018027
layout: post
message: ' '
