---
benchmark:
  id: 6b
  version: '0'
data:
- description: Free Energy Plot
  format:
    delimiter: ' '
    parse:
      free_energy: number
      time: number
    type: dsv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/9986ba35b6dfef5bdffef15db52de547/raw/ccb55df9b1a4d5b826fd4a8bb09c666336ad8d1c/energy.txt
- name: run_time
  values:
  - sim_time: '1000'
    wall_time: '4350'
- name: memory_usage
  values:
  - unit: KB
    value: '266000'
date: 1501621688
metadata:
  author:
    email: guyer@nist.gov
    first: Jon
    github_id: guyer
    last: Guyer
  hardware:
    acc_architecture: none
    clock_rate: '2.9'
    cores: '1'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: fipy
    repo:
      url: https://github.com/guyer/hackathonIII
      version: 0b52c55d
  simulation_name: fipy_6b_macbookpro
  summary: Serial benchmark with FiPy on Gmsh mesh with round right
  timestamp: 1 August, 2017
