_id: 07697cc0-0ea1-11ec-95db-e540ca6adff7
metadata:
  author:
    first: Jed Thynne
    last: Tabitha Gascoigne
    email: jackibarlowe@arcor.de
    github_id: Candy Gold
  timestamp: '24'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Jacki
    repo:
      url: >-
        https://funkhabari.ir/2021/07/26/valve-%d8%a7%d8%b3%d8%aa%db%8c%d9%85-%d8%af%da%a9-%d9%88-%d8%b3%d9%88%db%8c%db%8c%da%86-%d8%a8%d9%87-%d8%af%d9%86%d8%a8%d8%a7%d9%84-%d9%85%d8%ae%d8%a7%d8%b7%d8%a8%d8%a7%d9%86-%d9%85%d8%aa%d9%81%d8%a7/
      version: CH
    container_url: >-
      https://funkhabari.ir/2021/07/26/valve-%d8%a7%d8%b3%d8%aa%db%8c%d9%85-%d8%af%da%a9-%d9%88-%d8%b3%d9%88%db%8c%db%8c%da%86-%d8%a8%d9%87-%d8%af%d9%86%d8%a8%d8%a7%d9%84-%d9%85%d8%ae%d8%a7%d8%b7%d8%a8%d8%a7%d9%86-%d9%85%d8%aa%d9%81%d8%a7/
  hardware:
    cpu_architecture: sh3eb
    acc_architecture: gpu
    parallel_model: serial
    clock_rate: OT
    cores: '1'
    nodes: AU
benchmark:
  id: 8b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: EG
        sim_time: PU
  - name: memory_usage
    values:
      - unit: KB
        value: LB
date: 1630884531
