---
benchmark:
  id: 1b
  version: 1
data:
- name: run_time
  values:
  - sim_time: 1013318.2801021
    wall_time: 3720
- name: memory_usage
  values:
  - unit: MB
    value: 796
- format:
    parse:
      TotalEnergy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.TotalEnergy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/49d3f4ebc29a373687b3e7f4ec0b8219dd098cb7/hackathon_p1_square_NF_STA.csv
metadata:
  author:
    email: andrea.jokisaari@northwestern.edu
    first: A. M.
    github_id: amjokisaari
    last: Jokisaari
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 6
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://bitbucket.org/ajokisaari/coral
      version: e8fc74f
  summary: Information for the Benchmark1 problems
  timestamp: 6/28/2016
