_id: d2890ce0-5dcf-11e7-b188-cf9fe732c6e7
metadata:
  author: ''
  email: ''
  name: ''
  summary: ''
  timestamp: ''
  implementation:
    repo:
      url: ''
      version: ''
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: ''
    cores: '2'
    nodes: '1'
  software:
    version: ''
    repo:
      url: ''
      version: ''
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: ''
  - name: run_time
    url: ''
  - url: ''
  - values: ''
date: 1498853283
