---
benchmark:
  id: 1b
  version: 1
data:
- name: timestep
  values: 0.00740741
- name: run_time
  values:
  - sim_time: 0.0
    wall_time: 0.0
  - sim_time: 1.0
    wall_time: 1.0
  - sim_time: 5.0
    wall_time: 2.0
  - sim_time: 10.0
    wall_time: 3.0
  - sim_time: 20.0
    wall_time: 4.0
  - sim_time: 100.0
    wall_time: 11.0
  - sim_time: 200.0
    wall_time: 21.0
  - sim_time: 500.0
    wall_time: 48.0
  - sim_time: 1000.0
    wall_time: 92.0
  - sim_time: 2000.0
    wall_time: 183.0
  - sim_time: 3000.0
    wall_time: 273.0
  - sim_time: 10000.0
    wall_time: 882.0
- name: memory_usage
  values:
  - unit: KB
    value: 29928
- name: free_energy
  transform:
  - as: y
    expr: datum.value
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - time: 0.0
    value: 319.1087496
  - time: 1.0
    value: 318.8532431
  - time: 5.0
    value: 316.3930324
  - time: 10.0
    value: 297.6413587
  - time: 20.0
    value: 206.0186162
  - time: 100.0
    value: 116.9931797
  - time: 200.0
    value: 102.6644347
  - time: 500.0
    value: 82.53981151
  - time: 1000.0
    value: 69.7133687
  - time: 2000.0
    value: 52.2692085
  - time: 3000.0
    value: 47.20469271
  - time: 10000.0
    value: 27.72619387
metadata:
  author:
    email: stvdwtt@umich.edu
    first: Stephen
    github_id: stvdwtt
    last: DeWitt
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 2
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: prisms
    repo:
      url: https://github.com/prisms-center/phaseField/tree/master/applications/CHiMaD_benchmark1a
      version: acf1366651e0c9dab9108b0c881ca225730109e4
  summary: Flux cluster benchmark with PRISMS-PF
  timestamp: Fri, 10 Feb 2017 12:32:00 -0500
