_id: aa776110-13ed-11ec-8220-3f8c132c7f73
metadata:
  author:
    first: Norberto John
    last: Nadine Hadley
    email: haydenhalley@gmail.com
    github_id: Shantell McNamara
  timestamp: '10'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Hayden
    repo:
      url: >-
        https://jahankhabari.ir/2021/07/24/%d9%88%d8%b6%d8%b9%db%8c%d8%aa-%d8%a7%d8%b6%d8%b7%d8%b1%d8%a7%d8%b1%db%8c-%d8%af%d8%b1-%d8%aa%d9%88%d9%86%d8%b3-%db%b6-%d9%85%d8%a7%d9%87-%d8%af%db%8c%da%af%d8%b1-%d8%aa%d9%85%d8%af%db%8c%d8%af-%d8%b4/
      version: VU
    container_url: >-
      https://jahankhabari.ir/2021/07/24/%d9%88%d8%b6%d8%b9%db%8c%d8%aa-%d8%a7%d8%b6%d8%b7%d8%b1%d8%a7%d8%b1%db%8c-%d8%af%d8%b1-%d8%aa%d9%88%d9%86%d8%b3-%db%b6-%d9%85%d8%a7%d9%87-%d8%af%db%8c%da%af%d8%b1-%d8%aa%d9%85%d8%af%db%8c%d8%af-%d8%b4/
  hardware:
    cpu_architecture: mipsel
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: RM
    cores: '1'
    nodes: LJ
benchmark:
  id: 4f
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: DW
        sim_time: UC
  - name: memory_usage
    values:
      - unit: KB
        value: WP
date: 1631467203
