---
_id: 727d5e10-7705-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6a
  version: '0'
data:
- name: run_time
  values:
  - sim_time: '1000'
    wall_time: '40'
- name: memory_usage
  values:
  - unit: KB
    value: '164000'
- description: Free Energy Plot
  format:
    delimiter: ' '
    parse:
      free_energy: number
      time: number
    type: dsv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/db0d5558e0b60aeade766f0f847cfd06/raw/c0088b2f1cd67e8774b54150eab96b854de13c96/energy.txt
- description: Concentration cut-plane
  format:
    delimiter: ' '
    parse:
      c: number
      x: number
    type: dsv
  name: cut_plane_x_c
  transform:
  - as: y
    expr: datum.c
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/5f2bcef626be5597e3dbb3223c976a01/raw/3a07d49d1c0e6fbab50c3b3b4d00ccae7fb58d9b/gistfile1.txt
- description: Phi cut-plane
  format:
    delimiter: ' '
    parse:
      Phi: number
      x: number
    type: dsv
  name: cut_plane_x_phi
  transform:
  - as: y
    expr: datum.Phi
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/5f2bcef626be5597e3dbb3223c976a01/raw/3a07d49d1c0e6fbab50c3b3b4d00ccae7fb58d9b/gistfile1.txt
date: 1501625094
metadata:
  author:
    email: guyer@nist.gov
    first: Jon
    github_id: guyer
    last: Guyer
  hardware:
    acc_architecture: none
    clock_rate: '2.9'
    cores: '1'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: fipy
    repo:
      url: https://github.com/guyer/hackathonIII
      version: f0bc7b4
  simulation_name: fipy_6a_macbookpro
  summary: Serial benchmark with FiPy on uniform grid
  timestamp: 1 August, 2017
