_id: 727d5e10-7705-11e7-a3e9-cb63094aa20f
metadata:
  author: Jon Guyer
  email: guyer@nist.gov
  simulation_name: fipy_6a_macbookpro
  summary: Serial benchmark with FiPy on uniform grid
  timestamp: '1 August, 2017'
  implementation:
    repo:
      url: 'https://github.com/guyer/hackathonIII'
      version: f0bc7b4
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '2.9'
    cores: '1'
    nodes: '1'
  software:
    name: fipy
    version: 3.1.3.dev167+g8b4ec87c
    repo:
      url: 'https://github.com/usnistgov/fipy'
      version: ecbe868f2aff6
benchmark:
  id: 6a
  version: '0'
data:
  - name: run_time
    values:
      - wall_time: '40'
        sim_time: '1000'
  - name: memory_usage
    values:
      - unit: KB
        value: '164000'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/guyer/hackathonIII/master/Data/e0eb207f-5cbe-4327-a17e-babd70b8c701/energy.txt
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: cut_plane_x
    url: >-
      https://raw.githubusercontent.com/guyer/hackathonIII/master/Data/e0eb207f-5cbe-4327-a17e-babd70b8c701/y%3D50%40t%3D400.0.txt
    format:
      parse:
        x: number
        concentration: number
      type: csv
  - name: cut_plane_y
    url: ''
    format:
      parse:
        'y': number
        concentration: number
      type: csv
date: 1501625094
