_id: f3da21a0-61c5-11e7-81a9-f90aa26fd17e
metadata:
  author: ''
  email: ''
  simulation_name: ''
  summary: ''
  timestamp: ''
  implementation:
    repo:
      url: ''
      version: ''
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: ''
    cores: '1'
    nodes: '1'
  software:
    name: fenics
    version: ''
    repo:
      url: ''
      version: ''
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: ''
    format:
      parse:
        time: number
        free_energy: number
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - time: ''
        sim_time: ''
  - name: youtube
    url: ''
  - name: memory_usage
    values: ''
date: 1499288848
datum_inschrijving: '2017-07-05T21:07:28.902Z'
doet_mee: true
nieuwe_inschrijving: true
