_id: 90904cb0-5209-11e9-86a0-0b26cc9e6e60
metadata:
  author:
    first: 'Faical,Yannick,Palingwende'
    last: Congo
    email: faical.congo@nist.gov
    github_id: faical-yannick-congo
  timestamp: ''
  summary: ''
  implementation:
    name: ''
    repo:
      url: ''
      version: ''
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: ''
    cores: '1'
    nodes: ''
benchmark:
  id: 6b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: ''
        sim_time: ''
  - name: memory_usage
    values:
      - unit: KB
        value: ''
date: 1553853664
