_id: a316c700-5160-11e9-86a0-0b26cc9e6e60
metadata:
  author:
    first: ''
    last: ''
    email: ''
    github_id: ''
  timestamp: ''
  summary: ''
  implementation:
    name: ''
    repo:
      url: ''
      version: ''
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: ''
    cores: '1'
    nodes: ''
benchmark:
  id: 1a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: ''
        sim_time: ''
  - name: memory_usage
    values:
      - unit: KB
        value: ''
date: 1553781111
