---
benchmark:
  id: 1a
  version: 1
data:
- name: timestep
  values: 0.00195312
- name: free_energy
  transform:
  - as: free_energy
    expr: datum.energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - energy: 319.094
    time: 0
  - energy: 318.053
    time: 7.61719
  - energy: 314.632
    time: 15.2344
  - energy: 303.393
    time: 22.8516
  - energy: 277.709
    time: 30.4688
  - energy: 240.619
    time: 38.0859
  - energy: 215.533
    time: 45.7031
  - energy: 206.567
    time: 53.3203
  - energy: 201.415
    time: 60.9375
  - energy: 196.916
    time: 68.5547
  - energy: 192.545
    time: 76.1719
- name: run_time
  values:
  - sim_time: 192.545
    wall_time: 1125.39
- name: memory_usage
  values:
  - unit: KB
    value: 33984
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 2
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: mmsp
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/periodic/
      version: 05a5db5111d92b916d51e143adf068547c3a654d
  summary: Parallel Travis CI benchmark with MMSP, periodic domain
  timestamp: Tue, 10 Jan 2017 01:01:39 +0000
