---
benchmark:
  id: 1c
  version: 0
data: []
metadata:
  author:
    email: null
    first:
    github_id: wd15
    last:
    name:
  hardware:
    acc_architecture:
    clock_rate:
    cores:
    cpu_architecture:
    nodes:
    parallel_model:
  implementation:
    container_url: asfalfjk
    name: custom
    repo:
      url: https://github.com/usnistgov/pfhub
      version: asf987987
  summary: stuff
  timestamp: 2022-05-09T20:48:22Z
