---
benchmark:
  id: 1a
  version: 1
data: []
metadata:
  author:
    email:
    first:
    github_id: wd15
    last:
  hardware:
    acc_architecture:
    clock_rate:
    cores:
    cpu_architecture:
    nodes:
    parallel_model:
  implementation:
    container_url:
    name: fenics
    repo:
      url: https://github.com/usnistgov/pfhub
      version:
  summary: test5
  timestamp:
