benchmark:
  id: 2b
  version: 1
data:
- name: run_time
  values:
  - sim_time: 74169
    unit: s
    wall_time: 28320
- name: memory_usage
  values:
  - unit: GB
    value: 3.0
- format:
    parse:
      TotalEnergy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.TotalEnergy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/eba1e44ec25a2d9a906b2c802596778892b2f676/hackathon_p2_NF_STA_dfdt.csv
metadata:
  author: A. M. Jokisaari
  email: andrea.jokisaari@northwestern.edu
  github_id: ''
  hardware:
    cores: 20
    details:
    - name: clock rate
      values:
        rate: 2.3
        unit: GHz
    - name: processor
      values: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
  implementation:
    details:
    - name: time_stepper
      values: STA
    end_condition: Equilibrium, total energy fluctuated due to numerical noise
    repo:
      url: https://bitbucket.org/ajokisaari/coral
      version: e8fc74f
  software:
    name: moose
    version: Hedgehog (now Coral)
  summary: Metadata for the Benchmark2 problems
  timestamp: 6/28/2016
