_id: d4bc21b0-627e-11e7-abb2-050f30cdd33c
metadata:
  author: Daniel Wheeler
  email: daniel.wheeler2@gmail.com
  simulation_name: test_a_pull_request_name
  summary: Testing pull request name
  timestamp: '4 July, 2017'
  implementation:
    repo:
      url: >-
        https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/periodic/
      version: aaaaaaaaaa
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '1.2'
    cores: '1'
    nodes: '1'
  software:
    name: custom
    version: '1'
    repo:
      url: 'https://github.com/mesoscale/mmsp/tree/develop'
      version: '987234'
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1a_wrksttn.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: run_time
    values:
      - time: '1'
        sim_time: '1'
  - name: memory_usage
    values: '1'
date: 1499368253
