_id: b7e95490-f653-11e7-9233-11f0291e4532
metadata:
  author:
    first: Trevor
    last: Keller
    email: trevor.keller@nist.gov
    github_id: tkphd
  simulation_name: fipy_1a_travis_test
  timestamp: 'Tue, 10 Jan 2017 00:46:24 +0000'
  summary: 'Serial Travis CI benchmark with FiPy, periodic domain'
  implementation:
    name: fipy
    repo:
      url: >-
        https://github.com/usnistgov/FiPy-spinodal-decomposition-benchmark/tree/master/periodic/
      version: 944284638f00c3a411a71981d27becf97a2eb0e4
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '1'
    nodes: '1'
benchmark:
  id: 1a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1495.47'
        sim_time: '52.746625481564735'
  - name: memory_usage
    values:
      - unit: KB
        value: '470976'
date: 1515622509
