---
_id: 10b44d10-76fb-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6b
  version: '0'
data:
- description: Free Energy Plot
  format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/laagesen/ac2b5742ec1f2e50f25f6b9d8b4a0fc1/raw/7036afd1a6aeefea1478d11352ea1eec0f28c364/problem2b_out_l1_dtIA8_upload.csv
- name: run_time
  values:
  - sim_time: '400'
    wall_time: '545'
- name: memory_usage
  values:
  - unit: KB
    value: '340000'
date: 1501620635
metadata:
  author:
    email: Larry.Aagesen@inl.gov
    first: Larry
    github_id: laagesen
    last: Aagesen
  hardware:
    acc_architecture: none
    clock_rate: '2.8'
    cores: '3'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/dschwen/CHiMaD_Hackathon
      version: 4b543d98c423fa719d360c16edf70960477c09d7
  simulation_name: inl_moose_6b
  summary: Benchmark problem 6b, gmsh triangular elements with element target length
    1, Adaptive time stepping with IterationAdaptive, target iterations = 8
  timestamp: 27 July, 2017
