_id: b0d263d0-5cdf-11e7-8740-611bb057eb94
metadata:
  author: lkjlkj
  email: a@b.com
  timestamp: '3 June, 2017'
  summary: lkjlkj
  hardware:
    architecture: x86_64
    clock_rate: '3.5'
benchmark:
  id: 1a
data:
  name: lkjlkj
date: 1498750147
layout: post
aanwezig: true
nieuwe_inschrijving: true
doet_mee: true
datum_inschrijving: '2017-06-29T15:29:07.644Z'
