_id: a8631dc0-0bef-11ec-b1fa-d3c776e85aa2
metadata:
  author:
    first: Beatris Cardona
    last: Flossie Toney
    email: altonhutton@gmail.com
    github_id: Jenifer Goin
  timestamp: '13'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Alton
    repo:
      url: 'https://irmusic4.ir/id/1169/'
      version: SO
    container_url: 'https://irmusic4.ir/id/1169/'
  hardware:
    cpu_architecture: sh3eb
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: MJ
    cores: '1'
    nodes: ZO
benchmark:
  id: 2b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: FX
        sim_time: XF
  - name: memory_usage
    values:
      - unit: KB
        value: WK
date: 1630588449
