---
benchmark:
  id: 1b
  version: 1
data:
  - description: free energy data
    format:
      parse:
        sim_time: number
        free_energy: number
      type: csv
    name: free_energy
    transform:
      - as: y
        expr: datum.free_energy
        type: formula
      - as: x
        expr: datum.sim_time
        type: formula
    type: line
    url: https://ndownloader.figshare.com/files/10030003
  - name: run_time
    values:
      - sim_time: 200000
        wall_time: 7388
  - name: memory_usage
    values:
      - unit: KB
        value: 308224
metadata:
  author:
    email: null
    first:
    github_id: wd15
    last:
    name: Daniel Wheeler
  hardware:
    acc_architecture: none
    clock_rate: "1.48"
    cores: "1792"
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: threaded
  implementation:
    container_url:
    name: custom
    repo:
      url: https://github.com/usnistgov/hiperc
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100 with 9-point discrete Laplacian
  timestamp: 2022-05-11T21:08:24Z
