_id: 7aeaecb0-1de7-11ec-bcdd-4330dc37f41c
metadata:
  author:
    first: Madeleine Earsman
    last: Palma Heist
    email: alejandrina_lonon@zoho.com
    github_id: Marquis Rickel
  timestamp: '17'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Alejandrina
    repo:
      url: 'https://jahankhabari.ir'
      version: JG
    container_url: 'https://jahankhabari.ir'
  hardware:
    cpu_architecture: k1om
    acc_architecture: gpu
    parallel_model: serial
    clock_rate: BF
    cores: '1'
    nodes: WO
benchmark:
  id: 5b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: IR
        sim_time: LJ
  - name: memory_usage
    values:
      - unit: KB
        value: ZQ
date: 1632564057
