---
benchmark:
  id: 1c
  version: 1
data:
- name: run_time
  values:
  - sim_time: 10000.0
    wall_time: 231.957
- name: memory_usage
  values:
  - unit: MB
    value: 277.19
- format:
    parse:
      F: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.F
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/anonymous/898a197718cf02b643e78841e54dba41/raw/9c69964d354165708d508e3dc6655fb941d83da9/problem_1c_out.csv
metadata:
  author:
    email: daniel.schwen@inl.gov
    first: Daniel
    github_id: dschwen
    last: Schwen
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 4
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/dschwen/CHiMaD_Hackathon
      version: f6ec84570
  summary: Benchmark with MOOSE on macPro, T-shaped no-flux domain
  timestamp: 6/1/2017
