---
_id: b5714190-5594-11e9-be72-7d0374dc3210
metadata:
  author:
    first: Daniel
    last: Schwen
    email: daniel.schwen@inl.gov
    github_id: dschwen
  timestamp: '2 April, 2019'
  summary: >-
    Results for Benchmark problem 3a. Reducing the frequency of mesh adaptivity
    steps and running on a slightly better machine (Intel(R) Xeon(R) CPU
    E5-2687W 0 @ 3.10GHz)  than my >5year old desktop.
  implementation:
    name: moose
    repo:
      url: 'https://github.com/dschwen/moose/tree/benchmark'
      version: 43020158811429f8c23de6feca917c6d84cab5c8
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '3.1'
    cores: '6'
    nodes: '1'
benchmark:
  id: 3a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '16.953'
        sim_time: '1500'
  - name: memory_usage
    values:
      - unit: KB
        value: '435546.875'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/pfhub_3a.1_out.csv
    format:
      type: csv
      parse:
        time: number
        free_energy: number
    description: Free energy versus time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.free_energy
        as: 'y'
  - name: solid_fraction
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/pfhub_3a.1_out.csv
    format:
      type: csv
      parse:
        time: number
        solid_fraction: number
    description: Solid fraction versus time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.solid_fraction
        as: 'y'
  - name: tip_position
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/pfhub_3a.1_out.csv
    format:
      type: csv
      parse:
        time: number
        tip_pos: number
    description: Tip position versus time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.tip_pos
        as: 'y'
  - name: phase_field_1500
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/contour_1500.csv
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: Zero contour at t=1500s
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
date: 1554243280
