_id: 98cebb20-5dad-11e7-a4b9-2303293c4f5c
metadata:
  author: jhgjhgjhgjhg
  email: a@b
  name: kjhkjhkjh
  summary: kjhkjhkjhk
  timestamp: '15 June, 2017'
  implementation:
    repo:
      url: 'http://github.com'
      version: aaaaaaaaaa
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: serial
    clock_rate: '3.50'
    cores: '1'
    nodes: '1'
  software:
    name: 'on'
    version: '1'
    repo:
      url: 'http://github.com'
      version: aaaaaa
benchmark:
  version: '1'
  id: 1a
data:
  - name: free_energy
    url: 'http://github.com'
    format:
      type: 'on'
  - name: run_time
    url: 'http://github.com'
  - url: 'https://www.youtube.com/watch?v=Kfrv7K9U5do'
  - values: '100'
date: 1498838583
