_id: b987fc70-30ba-11ec-af73-b3f4df2f002e
metadata:
  author:
    first: Rosalinda Khan
    last: Lisa Deaton
    email: rosauratalarico@gmail.com
    github_id: Jamison Thiessen
  timestamp: '23'
  summary: 'PFHub: The Phase Field Community Hub'
  implementation:
    name: Rosaura
    repo:
      url: 'http://http://'
      version: FS
    container_url: 'http://http://'
  hardware:
    cpu_architecture: m68k
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: JR
    cores: '1'
    nodes: RO
benchmark:
  id: 5a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: BL
        sim_time: AL
  - name: memory_usage
    values:
      - unit: KB
        value: OP
date: 1634633907
