---
# Used for workflows that are required to run after a pull request
# closes.
name: pullrequest-close
on:
  pull_request:
    types: [closed]
jobs:
  pullrequest-close:
    uses: usnistgov/pfhub/.github/workflows/pr-artifact.yml@workflow
    with:
      login: ${{ github.event.pull_request.user.login }}
      pr_number: ${{ github.event.number }}
